// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGR58G0sC-g1GCVF987K26PPVjMdnrW6k',
    appId: '1:721575829337:web:469328276347ee71237648',
    messagingSenderId: '721575829337',
    projectId: 'task-app-eb75e',
    authDomain: 'task-app-eb75e.firebaseapp.com',
    storageBucket: 'task-app-eb75e.appspot.com',
    measurementId: 'G-GRM4PLE7ZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbnQ6_1fqiFdPB_ldLNKw3r2RyZav36sg',
    appId: '1:721575829337:android:1f83827bdd515b7d237648',
    messagingSenderId: '721575829337',
    projectId: 'task-app-eb75e',
    storageBucket: 'task-app-eb75e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAc0Nu1nrEedo5kbo8jBRJ8hTHZ5Ek2nEw',
    appId: '1:721575829337:ios:604bb3c308f5c10a237648',
    messagingSenderId: '721575829337',
    projectId: 'task-app-eb75e',
    storageBucket: 'task-app-eb75e.appspot.com',
    iosBundleId: 'com.example.tasksApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAc0Nu1nrEedo5kbo8jBRJ8hTHZ5Ek2nEw',
    appId: '1:721575829337:ios:41050b1cc1a423cf237648',
    messagingSenderId: '721575829337',
    projectId: 'task-app-eb75e',
    storageBucket: 'task-app-eb75e.appspot.com',
    iosBundleId: 'com.example.tasksApp.RunnerTests',
  );
}
